base:
  project: Haresh-project
  random_state: 42
  target_col: Process_temperature_[K]

data_source:
  s3_source: data_given/ai4i2020.csv

load_data:
  raw_dataset_csv: data/raw/ai4i2020.csv

split_data:
  train_path: data/processed/train_ai4i2020.csv
  test_path: data/processed/test_ai4i2020.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      # alpha: 0.88
      # l1_ratio: 0.89
      alpha: 0.9
      l1_ratio: 0.4
model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.joblib